### ISSUE TITLE
test_hooks_bot.py not surpport pc client sent massage very good！

### ISSUE THREAD

**Issue by zbx911** [DeachSword/CHRLINE#21]
recvMessage {1: 438, 2: 1641818031141, 3: 26, 4: 0, 10: '0', 20: {1: 'u33667fda0fe9ad8exxxx9a204e2e47d', 2: 'u0abc2582d3d9ba69c6eb5bf73c7cb2bd', 3: 0, 4: '15396315862160', 5: 1641818031138, 14: False, 15: 0, 18: {'e2eeMark': '1', 'contentType': '0', 'e2eeVersion': '1'}, 19: [], 20: 44, 27: 4, 'opType': 26, 'isE2EE': False}}
python-BaseException
Traceback (most recent call last):
  File "D:\PyCharm 2020.3.1\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
Traceback (most recent call last):
  File "D:\Anaconda3_x64_2021_11\lib\threading.py", line 910, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm 2020.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    self._target(*self._args, **self._kwargs)
  File "F:\line\line_caller\CHRLINE_src\hooks.py", line 59, in trace
    exec(compile(contents+"\n", file, 'exec'), glob, loc)    if _func(self, data, cl):
  File "F:\line\line_caller\CHRLINE_src\hksc\types.py", line 22, in __check
  File "F:/line/line_caller/0.test_func.py", line 205, in <module>
    func(self, args[0], args[1])
  File "F:/line/line_caller/0.test_func.py", line 103, in recvMessage
    tracer.run()
  File "F:\line\line_caller\CHRLINE_src\hooks.py", line 34, in run
    self.trace(msg, self.HooksType["Content"], cl)
  File "F:\line\line_caller\CHRLINE_src\hooks.py", line 59, in trace
    self.runByClient(self.cl)
  File "F:\line\line_caller\CHRLINE_src\hooks.py", line 38, in runByClient
        for op in cl._Poll__fetchOps():if _func(self, data, cl):
  File "F:\line\line_caller\CHRLINE_src\poll.py", line 14, in __fetchOps
  File "F:\line\line_caller\CHRLINE_src\hksc\types.py", line 34, in __check
    opType = op[3]    
func(self, args[0], args[1])KeyError: 
  File "F:/line/line_caller/0.test_func.py", line 155, in TextMessage
3
    self.trace(msg, self.HooksType['Command'], cl)
  File "F:\line\line_caller\CHRLINE_src\hooks.py", line 59, in trace
    if _func(self, data, cl):
  File "F:\line\line_caller\CHRLINE_src\hksc\types.py", line 60, in __check
    text = self.cl.decryptE2EETextMessage(msg, msg.get('opType', 26) == 25)
  File "F:\line\line_caller\CHRLINE_src\e2ee.py", line 184, in decryptE2EETextMessage
    for i in range(len(chunks)):
TypeError: object of type 'int' has no len()
python-BaseException

**Comment by WEDeach** [comment]
Fixed on bd1cb7e934b8f3cef8daffdc731e838d3aa88d2d
