### ISSUE TITLE
getSquareChatMembers

### ISSUE THREAD

**Issue by betteray** [DeachSword/CHRLINE#42]
Traceback (most recent call last):
  File "/Users/ray/Documents/work/CHRLINE/examples/LineApi.py", line 153, in <module>
    api.getSquareMembers()
  File "/Users/ray/Documents/work/CHRLINE/examples/LineApi.py", line 129, in getSquareMembers
    resp = self.cl.getSquareChatMembers("s5735dba73045027e9a9eecf955878632")
  File "/Users/ray/Documents/work/CHRLINE/CHRLINE/services/SquareService.py", line 475, in getSquareChatMembers
    return self.postPackDataAndGetUnpackRespData(self.LINE_SQUARE_ENDPOINT, sqrd, self.SquareService_RES_TYPE, encType=0, baseException=SquareService.SQUARE_EXCEPTION)
  File "/Users/ray/Documents/work/CHRLINE/CHRLINE/models.py", line 518, in postPackDataAndGetUnpackRespData
    tmore = self.TMoreCompactProtocol(
  File "/Users/ray/Documents/work/CHRLINE/CHRLINE/thrift.py", line 609, in __init__
    self.d(a)               # for data
  File "/Users/ray/Documents/work/CHRLINE/CHRLINE/thrift.py", line 640, in d
    return self.t()     # base init?
  File "/Users/ray/Documents/work/CHRLINE/CHRLINE/thrift.py", line 836, in t
    self.m()                                            # base init
  File "/Users/ray/Documents/work/CHRLINE/CHRLINE/thrift.py", line 776, in m
    self.__e.append(bytes(bArr).decode())                       # wow magic
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte

I had changed the method to avoid some errors:

```
def getSquareChatMembers(self, squareChatMid: str, continuationToken: str = None, limit: int = 200):
        GetSquareChatMembersRequest = [
            [11, 1, squareChatMid],
            [8, 3, limit]
        ]
        if continuationToken is not None:
            GetSquareChatMembersRequest.append(
                [11, 2, continuationToken])
        params = [
            [12, 1, GetSquareChatMembersRequest]
        ]
        sqrd = self.generateDummyProtocol("getSquareChatMembers", params, self.SquareService_REQ_TYPE)
        return self.postPackDataAndGetUnpackRespData(self.LINE_SQUARE_ENDPOINT, sqrd, self.SquareService_RES_TYPE, encType=0, baseException=SquareService.SQUARE_EXCEPTION)

```

**Comment by betteray** [comment]
I have fixed it by changing the response type:

```
    def getSquareChatMembers(self, squareChatMid: str, continuationToken: str = None, limit: int = 200):
        GetSquareChatMembersRequest = [
            [11, 1, squareChatMid],
            [8, 3, limit]
        ]
        if continuationToken is not None:
            GetSquareChatMembersRequest.append(
                [11, 2, continuationToken])
        params = [
            [12, 1, GetSquareChatMembersRequest]
        ]
        sqrd = self.generateDummyProtocol("getSquareChatMembers", params, 4)
        return self.postPackDataAndGetUnpackRespData(self.LINE_SQUARE_ENDPOINT, sqrd, 4, encType=0, baseException=SquareService.SQUARE_EXCEPTION)

```

btw, the `self.SquareService_REQ_TYPE` , `self.SquareService_API_PATH`, `self.SquareService_RES_TYPE` were not defined.

**Comment by WEDeach** [comment]
yups, SquareService is only responsive compact
