### ISSUE TITLE
can't not read type 0 on noop response

### ISSUE THREAD

**Issue by hans00** [DeachSword/CHRLINE#53]
With my inspection `noop` response payload is `b'\x82A\x00\x04noop\x00'`

And it crash on data read

```
Traceback (most recent call last):
  File "/root/test.py", line 4, in <module>
    print(Thrift.TCompactProtocol(None, b'\x82A\x00\x04noop\x00'))
  File "/usr/local/lib/python3.10/dist-packages/CHRLINE/thrift.py", line 266, in __init__
    self.x()
  File "/usr/local/lib/python3.10/dist-packages/CHRLINE/thrift.py", line 474, in x
    data, d = self.z(ftype, fid)
  File "/usr/local/lib/python3.10/dist-packages/CHRLINE/thrift.py", line 563, in z
    raise Exception(f"can't not read type {ftype}")
Exception: can't not read type 0
```

**Comment by hans00** [comment]
I'm not sure add this check is correct fix

```diff
451a452,455
>             if self.__last_pos >= len(self.data):
>                 self.res = data
>                 self.dummyProtocol = d
>                 return
```

**Comment by WEDeach** [comment]
It missed an important logic: `elif`

In Thrift, type 0 means None (or end).
so proper logic to handle it would be better (ouob

It would be appreciated if you could check it works.
