### ISSUE TITLE
Primary Register Issue

### ISSUE THREAD

**Issue by winbotscript** [DeachSword/CHRLINE#63]
Help me please for this issue:

[root@jpn chrlinebot]# python3 test_register.py
private_key: b'oDXTluX2NRZRpu03klALvzqqoFK9Ho/303B/grwlEGA='
public_key: b'5VZib6Lg6IhQYiSQPGMCGX7r6+/z1COr1xoDGorcKUw='
nonce: b'jRF/8rgR4jRl/27jZ54yPA=='
[SESSION] lh4JY9mHLXyOSOaxDEa3DW2ptoaAf3ny
input your phone number(0936....): 089510183xxx
input phone number region(TW or JP or...): ID
{'error': {'code': 101, 'message': 'The latest version of LINE is needed to continue. Please update LINE and try again.', 'metadata': None, '_data': {1: 101, 2: 'The latest version of LINE is needed to continue. Please update LINE and try again.'}}}
Traceback (most recent call last):
  File "test_register.py", line 85, in <module>
    phone2 = cl.getPhoneVerifMethodV2(session, phone, region)
  File "/mnt/d/botline/chrlinebot/CHRLINE/services/PrimaryAccountInitService.py", line 168, in getPhoneVerifMethodV2
    return self.postPackDataAndGetUnpackRespData("/acct/pais/v1" ,sqrd, 3, headers=self.register_headers)
  File "/mnt/d/botline/chrlinebot/CHRLINE/models.py", line 650, in postPackDataAndGetUnpackRespData
    raise LineServiceException(res["error"])
CHRLINE.exceptions.LineServiceException: Code: 101, Message: The latest version of LINE is needed to continue. Please update LINE and try again.

**Comment by winbotscript** [comment]
Solved, thanks :)

**Comment by winbotscript** [comment]
Solved, thanks :)
