### ISSUE TITLE
LineServiceException: Must upgrade

### ISSUE THREAD

**Issue by huskyy8y8** [DeachSword/CHRLINE#69]
{'error': {'code': 50, 'message': 'Must upgrade', 'metadata': None, 'raw': TalkException(code=50, reason='Must upgrade', parameterMap=None)}}
Traceback (most recent call last):
  File "testchrline.py", line 4, in <module>
    cl = CHRLINE(useThrift=True)
  File "/usr/local/lib/python3.8/dist-packages/CHRLINE/client.py", line 125, in __init__
    self.initAll()
  File "/usr/local/lib/python3.8/dist-packages/CHRLINE/client.py", line 129, in initAll
    self.profile = self.getProfile()
  File "/usr/local/lib/python3.8/dist-packages/CHRLINE/services/TalkService.py", line 303, in getProfile
    return self.postPackDataAndGetUnpackRespData(
  File "/usr/local/lib/python3.8/dist-packages/CHRLINE/models.py", line 650, in postPackDataAndGetUnpackRespData
    raise LineServiceException(res["error"])
CHRLINE.exceptions.LineServiceException: Code: 50, Message: Must upgrade

**Comment by WEDeach** [comment]
Hi @huskyy8y8,

just follow same point:
https://github.com/DeachSword/CHRLINE/blob/b08a9f2c186c0e7d4ee2e2bfc6f83e2c8915a9b5/CHRLINE/client.py#L136

And I can't provide you with the correct version, please look it up yourself.
Becareful If you use an incorrect version to login, your account may be banned
